name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      matrix:
        node-version: [16.x]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2

      - name: Install client npm packages
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build client
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
